import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

void main(List<String> args) {
  final file = File('test/fixtures/unicode/NormalizationTest.txt');
  final bytes = file.readAsBytesSync();
  final rows = <List<String>>[];
  for (final line in utf8.decode(bytes).split('\n')) {
    final text = line.split('#').first.trim();
    if (text.isEmpty || text.startsWith('@')) continue;
    rows.add(
      text
          .split(';')
          .take(5)
          .map(
            (part) => String.fromCharCodes(
              part
                  .trim()
                  .split(RegExp(r'\s+'))
                  .map((code) => int.parse(code, radix: 16)),
            ),
          )
          .toList(),
    );
  }
  final payload = jsonEncode(rows);
  final content =
      '// Generated by tool/embed_unicode.dart. Do not edit.\n'
      '// Unicode 17.0 NormalizationTest.txt SHA256: ${sha256.convert(bytes)}\n'
      '// dart format off\nconst unicodeJson = ${jsonEncode(payload).replaceAll(r'$', r'\$')};\n';
  final output = File('test/fixtures/unicode.dart');
  if (args.contains('--check')) {
    if (output.readAsStringSync() != content) {
      throw StateError('Unicode fixture mismatch');
    }
  } else {
    output.writeAsStringSync(content);
  }
  stdout.writeln('${rows.length} Unicode conformance rows');
}
