import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

void main(List<String> args) {
  final buffer = StringBuffer(
    '// Generated by tool/embed_fixtures.dart. Do not edit.\n// dart format off\n',
  );
  for (final name in ['golden', 'classifier', 'layers', 'rules', 'mutations']) {
    final payload = File('test/fixtures/$name.json').readAsStringSync().trim();
    buffer.writeln('// SHA256: ${sha256.convert(utf8.encode(payload))}');
    buffer.writeln(
      'const ${name}Json = ${jsonEncode(payload).replaceAll(r'$', r'\$')};',
    );
  }
  final file = File('test/fixtures/embedded.dart');
  if (args.contains('--check')) {
    if (file.readAsStringSync() != buffer.toString()) {
      throw StateError('Embedded fixtures differ');
    }
  } else {
    file.writeAsStringSync(buffer.toString());
  }
}
