import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

import 'fixture_validation.dart';

void main(List<String> args) {
  final payload = File('test/fixtures/full.json').readAsStringSync().trim();
  validateFullCorpus((jsonDecode(payload) as Map).cast<String, Object?>());
  final content =
      '// Generated by tool/embed_full.dart. Do not edit.\n'
      '// SHA256: ${sha256.convert(utf8.encode(payload))}\n// dart format off\n'
      'const fullJson = ${jsonEncode(payload).replaceAll(r'$', r'\$')};\n';
  final file = File('test/fixtures/full.dart');
  if (args.contains('--check')) {
    if (file.readAsStringSync() != content) {
      throw StateError('Full fixture mismatch');
    }
  } else {
    file.writeAsStringSync(content);
  }
}
