import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const data = 'tool/data';

String literal(String value) => jsonEncode(value).replaceAll(r'$', r'\$');
Object? readJson(String path) => jsonDecode(File(path).readAsStringSync());

void main(List<String> args) {
  final manifest = readJson('$data/manifest.json') as Map;
  var sourceCount = 0;
  for (final entry in manifest['files'] as List) {
    sourceCount++;
    final path = '$data/${entry['path']}';
    final bytes = File(path).readAsBytesSync();
    if (bytes.length != entry['bytes'] ||
        sha256.convert(bytes).toString() != entry['sha256']) {
      throw StateError('Frozen source mismatch: $path');
    }
  }
  final rulesPath = '$data/declension-rules.json';
  final rules = readJson(rulesPath) as List;
  if (rules.length != 99) throw StateError('Expected 99 rules');
  final expanded = <Object?>[];
  for (final name in ['adjective', 'exception', 'noun']) {
    var text = File('$data/$name-declension-rules.json').readAsStringSync();
    for (final entry in {
      '[апостроф]': "['’ʼ]",
      '[голосний]': '[аеєиіїоуюя]',
      '[приголосний]': '([бвгґджзйклмнпрстфхцчшщ]|дз|дж)',
      '[твердий_приголосний]': '([бвгґджзклмнпрстфхцчшщ]|дз|дж)',
      '[губний_приголосний]': '[бпвмф]',
    }.entries) {
      text = text.replaceAll(entry.key, entry.value);
    }
    expanded.addAll(jsonDecode(text) as List);
  }
  final ordered = expanded.indexed.toList()
    ..sort((a, b) {
      final difference = ((b.$2 as Map)['priority'] as int).compareTo(
        (a.$2 as Map)['priority'] as int,
      );
      return difference == 0 ? a.$1.compareTo(b.$1) : difference;
    });
  if (jsonEncode(ordered.map((e) => e.$2).toList()) != jsonEncode(rules)) {
    throw StateError('Compiled rules do not match upstream macro expansion');
  }
  const cases = [
    'nominative',
    'genitive',
    'dative',
    'accusative',
    'ablative',
    'locative',
    'vocative',
  ];
  for (final rule in rules) {
    if (!['noun', 'adjective'].contains(rule['wordClass']) ||
        rule['priority'] is! int) {
      throw StateError('Invalid rule');
    }
    for (final gender in rule['gender'] as List) {
      if (!['masculine', 'feminine'].contains(gender)) {
        throw StateError('Invalid gender');
      }
    }
    for (final application in rule['applicationType'] as List) {
      if (![
        'givenName',
        'patronymicName',
        'familyName',
      ].contains(application)) {
        throw StateError('Invalid application');
      }
    }
    for (final name in cases) {
      for (final commands in rule['grammaticalCases'][name] as List) {
        for (final entry in (commands as Map).entries) {
          if (int.parse(entry.key as String) < 0 ||
              !['append', 'replace'].contains(entry.value['action']) ||
              entry.value['value'] is! String) {
            throw StateError('Invalid command');
          }
        }
      }
    }
  }
  final bundle = readJson('$data/model.bundle.json') as Map;
  final shapes = (bundle['weightSpecs'] as List)
      .map((entry) => entry['shape'])
      .toList();
  if (jsonEncode(shapes) != '[[34,16],[16,16],[16,16],[16],[16,1],[1]]' ||
      (bundle['weightSpecs'] as List).any(
        (entry) => entry['dtype'] != 'float32',
      )) {
    throw StateError('Unsupported model weights');
  }
  final layers = bundle['modelTopology']['config']['layers'] as List;
  if (layers.map((e) => e['class_name']).join(',') !=
          'Embedding,SimpleRNN,Dense' ||
      layers[1]['config']['activation'] != 'relu' ||
      layers[2]['config']['activation'] != 'sigmoid') {
    throw StateError('Unsupported topology');
  }
  final bytes = base64Decode(bundle['weightData'] as String);
  if (bytes.length != 4356 ||
      sha256.convert(bytes).toString() !=
          'e7b89fc461b3c1f2c42cc31580bdbfcde2217ebb321457c1b65aca503c18da36' ||
      base64Encode(File('$data/weights.bin').readAsBytesSync()) !=
          bundle['weightData']) {
    throw StateError('Model bytes mismatch');
  }
  final output = StringBuffer(
    '// Generated by tool/generate_data.dart. Do not edit.\n'
    '// Frozen data hashes: tool/data/manifest.json.\n'
    '// dart format off\n'
    "import '../declension.dart';\n",
  );
  output.writeln(
    'const _defaultRulesData = <Map<String, Object?>>${jsonEncode(rules).replaceAll(r'$', r'\$')};',
  );
  output.writeln(
    'final defaultRules = List<DeclensionRule>.unmodifiable(_defaultRulesData.map(DeclensionRule.fromJson));',
  );
  final maps = {
    'givenGenderPatterns': '$data/given-name-rules.json',
    'patronymicGenderPatterns': '$data/patronymic-name-rules.json',
    'surnameOverrides': '$data/incorrect-predictions.json',
  };
  for (final entry in maps.entries) {
    output.writeln('const ${entry.key} = <String, String>{');
    for (final value in (readJson(entry.value) as Map).entries) {
      output.writeln(
        '${literal(value.key as String)}: ${literal(value.value as String)},',
      );
    }
    output.writeln('};');
  }
  for (final entry in {
    'militaryClassifierRules': 'word-classifier-rules.json',
    'militaryHyphenationRules': 'word-hyphenation-rules.json',
  }.entries) {
    output.writeln(
      'const ${entry.key} = <Map<String, Object>>${jsonEncode(readJson('$data/${entry.value}')).replaceAll(r'$', r'\$')};',
    );
  }
  output.writeln(
    'const modelWeights = ${literal(bundle['weightData'] as String)};',
  );
  final file = File('lib/src/generated/data.dart');
  if (args.contains('--check')) {
    if (!file.existsSync() || file.readAsStringSync() != output.toString()) {
      throw StateError('Generated data differs');
    }
  } else {
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(output.toString());
  }
  stdout.writeln(
    'Verified $sourceCount frozen files, 99 rules and 4356 model bytes.',
  );
}
